//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tekapo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tekapo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;yyyy&gt;&lt;MM&gt;&lt;dd&gt;-&lt;HH&gt;&lt;mm&gt;&lt;ss&gt;.
        /// </summary>
        internal static string DefaultRenameFormat {
            get {
                return ResourceManager.GetString("DefaultRenameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name format specified is invalid..
        /// </summary>
        internal static string ErrorNameFormatInvalid {
            get {
                return ResourceManager.GetString("ErrorNameFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been selected for processing..
        /// </summary>
        internal static string ErrorNoFilesSelected {
            get {
                return ResourceManager.GetString("ErrorNoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name format has been specified..
        /// </summary>
        internal static string ErrorNoNameFormatProvided {
            get {
                return ResourceManager.GetString("ErrorNoNameFormatProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regular expression format has been specified..
        /// </summary>
        internal static string ErrorNoRegularExpressionProvided {
            get {
                return ResourceManager.GetString("ErrorNoRegularExpressionProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search path has been specified..
        /// </summary>
        internal static string ErrorNoSearchPathProvided {
            get {
                return ResourceManager.GetString("ErrorNoSearchPathProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No time shift values have been specified. At least one of the fields must not equal 0..
        /// </summary>
        internal static string ErrorNoTimeShiftProvided {
            get {
                return ResourceManager.GetString("ErrorNoTimeShiftProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wildcard format has been specified..
        /// </summary>
        internal static string ErrorNoWildcardProvided {
            get {
                return ResourceManager.GetString("ErrorNoWildcardProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regular expression format specified is invalid.
        ///
        ///{0}.
        /// </summary>
        internal static string ErrorRegularExpressionInvalid {
            get {
                return ResourceManager.GetString("ErrorRegularExpressionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search path specified does not exist..
        /// </summary>
        internal static string ErrorSearchPathDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorSearchPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files failed to be processed..
        /// </summary>
        internal static string FailedProcessedResultsFormat {
            get {
                return ResourceManager.GetString("FailedProcessedResultsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 of 3: Searching for directories.
        /// </summary>
        internal static string FileSearchDirectoryTitle {
            get {
                return ResourceManager.GetString("FileSearchDirectoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 of 3: Filtering files.
        /// </summary>
        internal static string FileSearchFileFilterTitle {
            get {
                return ResourceManager.GetString("FileSearchFileFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 of 3: Calculating files.
        /// </summary>
        internal static string FileSearchFileTitle {
            get {
                return ResourceManager.GetString("FileSearchFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://neovolve.com/.
        /// </summary>
        internal static string HelpAddress {
            get {
                return ResourceManager.GetString("HelpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///
        ///{0} will be renamed to {1}.
        /// </summary>
        internal static string NameFormatExample {
            get {
                return ResourceManager.GetString("NameFormatExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///
        ///The format specified is not valid..
        /// </summary>
        internal static string NameFormatExampleInvalidFormat {
            get {
                return ResourceManager.GetString("NameFormatExampleInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///
        ///No name format specified..
        /// </summary>
        internal static string NameFormatExampleNoFormatAvailable {
            get {
                return ResourceManager.GetString("NameFormatExampleNoFormatAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:
        ///
        ///No valid files found for processing..
        /// </summary>
        internal static string NameFormatExampleNoValidFile {
            get {
                return ResourceManager.GetString("NameFormatExampleNoValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing command line arguments..
        /// </summary>
        internal static string ParseCommandLineArguments {
            get {
                return ResourceManager.GetString("ParseCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed {0} to {1}..
        /// </summary>
        internal static string RenameProcessFormat {
            get {
                return ResourceManager.GetString("RenameProcessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a path to search..
        /// </summary>
        internal static string SelectPathDescription {
            get {
                return ResourceManager.GetString("SelectPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string SkipButtonText {
            get {
                return ResourceManager.GetString("SkipButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were successfully processed..
        /// </summary>
        internal static string SuccessfulProcessedResultsFormat {
            get {
                return ResourceManager.GetString("SuccessfulProcessedResultsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifting time for {0}..
        /// </summary>
        internal static string TimeShiftProcessFormat {
            get {
                return ResourceManager.GetString("TimeShiftProcessFormat", resourceCulture);
            }
        }
    }
}
